### PR TITLE
Update for JupyterLab 3.0

### LINKED ISSUE #316: JupyterLab 3.0 support?
Hi, JupyterLab 3.0 has been released recently and it would be very nice to see your extension ported. There is an automated script that can help to get you started: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

I really hope to see the version 1.0 soon :)

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #316

### Changes

- [x] Upgrade to JupyterLab 3.0
- [x] Implement pip-installable federated extension so users can install the extension without installing Node.js 
- [x] Remove dependencies on tde forks of lumino and jupyterlab packages
- [x] Update readme to include new installation instructions

### CODE REVIEW

**Comment by krassowski** [comment]
The port to JupyterLab 3.0 is ready. Some things worth noting:
- there might be regressions, I have not tested it thoroughly (but I do see that it looks different than on the show off gifs); I can guarantee that it complies and the basic functionality works, but not that it works the same as on 2.x (I have not used it on 2.x)
- enzyme-adapter-react-16 was replaced with @wojtekmaj/enzyme-adapter-react-17 (no official support for React 17 just yet)
- there are some eslint warnings on typing which look like easy wins:

```
/home/runner/work/jupyterlab-tabular-data-editor/jupyterlab-tabular-data-editor/src/litestore.ts
Warning:   669:5  warning  Argument 'thisArg' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
Warning:   686:5  warning  Argument 'thisArg' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
Warning:   703:5  warning  Argument 'thisArg' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types

/home/runner/work/jupyterlab-tabular-data-editor/jupyterlab-tabular-data-editor/src/model.ts
Warning:   295:5  warning  Argument 'values' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
```

I also recommend adding an `publish.yml` action to make the releases smoother( see e.g. [publish.yml](https://github.com/krassowski/jupyterlab-spreadsheet-editor/pull/17/files#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7)).

**Review by lmcnichols — APPROVED** [review]
Looks good!

**Comment by Zsailer** [comment]
@lmcnichols, would you mind publishing a release with this update?

Or would you mind adding me (@Zsailer) and @krassowski as maintainers on the npm package?

**Comment by lmcnichols** [comment]
@kgoo124 can you add @Zsailer & @krassowski as maintainers to the npm package for our extension? Thanks!

**Comment by kgoo124** [comment]
@Zsailer @krassowski you both should be added as maintainers. curious as to what the future plans for the extension will be. will you both be taking it up?

**Pull request merged**
