### PR TITLE
Add publish action

### LINKED ISSUE #318: Uploading to PYPI
Now there is support for jupyterlab3 and it is available as a python package is there a plan to upload it to PYPI?

### PR DESCRIPTION
**Pull request by krassowski**
### Issue being fixed:
Fixes #318

### Changes proposed:

- add publish action to automate releases

### CODE REVIEW

**Comment by krassowski** [comment]
I cannot add tokens here, but happy to invite anyone who can to the PyPI project.

**Comment by kgoo124** [comment]
@krassowski working on giving you npm package and repo permissions right now. Would you be able to explain how the automation of the releases works? I'm not too familiar with this.

**Review by kgoo124 — APPROVED** [review]
LGTM, this will definitely help out!

**Comment by krassowski** [comment]
Once the authentication tokens are added you just tag a release using GitHub GUI and the publish action takes care of it for you. You stil need to bump the version in package.json prior to that though.

**Comment by kgoo124** [comment]
Okay, that makes sense. I don't think I can add authentication tokens right? If I can, I'm happy to do that. Just let me know how to go about it.

**Comment by krassowski** [comment]
Do you see "Secrets" section in settings? If not, then someone with "admin" rights on this repository needs to do it (@Zsailer?).

Screenshot from 2021-03-24 18-48-08

More info: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by kgoo124** [comment]
@krassowski sent you a Gitter message. I think it would quicker to work this out if you can hop on a call.

**Comment by kgoo124** [comment]
@Zsailer got it all settled out. cutting a new release right now

**Pull request merged**
